name: Render and bundle docs

on:
  push:
    branches:
      - master

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout https://github.com/carnarez/polars-unpack repository
        uses: actions/checkout@v3

      - name: Set up Node v16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install Node dependencies
        run: |
          npm install --global --no-audit --no-fund \
            autoprefixer \
            clean-css-cli \
            html-minifier \
            postcss-cli \
            terser

      - name: Set up Python v3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --no-cache-dir \
            ghp-import \
            git+https://github.com/carnarez/astdocs@master \
            git+https://github.com/carnarez/markdown-astdocs@master \
            git+https://github.com/carnarez/markdown-img@master \
            git+https://github.com/carnarez/markdown-insert@master \
            git+https://github.com/carnarez/markdown-script@master \
            jinja2 \
            lunr \
            markdown \
            pymdown-extensions \
            pyyaml

      - name: Render and bundle
        run: |
          # generate the documentation
          mkdir web/{api,tests}
          cp README.md web/index.md
          cp polars_unpack/unpack.py web/api
          cp tests/test_*.py web/tests
          (
            cd web/api
            ASTDOCS_WITH_LINENOS=1 astdocs unpack.py > index.md
            mv *.py ..
          )
          (
            cd web/tests
            ASTDOCS_WITH_LINENOS=1 astdocs . > index.md
            mv *.py ..
          )
          # render the documentation
          (
            cd web
            # will contain all rendered/bundled content
            mkdir www
            # where to find the templates (base url)
            url=https://raw.githubusercontent.com/carnarez/markdown-render/master
            # download the stylesheets
            wget $url/style/style.css -O _style.css
            wget $url/style/style-highlight.css -O _style-highlight.css
            wget $url/style/style-markdown.css -O _style-markdown.css
            wget $url/style/style-search.css -O _style-search.css
            # prepare markdown files
            rm README.md
            find . -name "*.md" | grep -e front-matter.md -e toc.md -v | while read f; do
              mkdir -p /tmp/www/$(dirname $f)
              cat front-matter.md $f > /tmp/md
              mv /tmp/md $f
            done
            rm front-matter.md
            # convert markdown to html
            wget $url/build/render.py
            wget $url/build/template.html
            python render.py --prefix=/tmp/www \
                             --root=https://carnarez.github.io/polars-unpack/ \
                             $(find . -name "*.md" | grep -v toc.md)
            rm toc.md
            # generate the splash 
            python unpack_logo.py polars-logo.svg > /tmp/www/splash.svg
            # modify html links
            sed -i 's|href=\"/|href=\"/polars-unpack/|g;s|src=\"/|src=\"/polars-unpack/|g' $(find /tmp/www -name "*.html")
            # prepare css files
            cat _style.css _style-*.css | grep -v '@import ".*"' > _bundle.css
            rm _style.css _style-*.css
            cat *.css > /tmp/www/style.css
            rm *.css
            find . -name "*.css" | while read f; do
              cp $f /tmp/www/$(dirname $f)
            done
            # prepare js files
            find . -name "*.js" | while read f; do
              cp $f /tmp/www/$(dirname $f)
            done
          )
          # minify everything
          (
            cd /tmp/www
            # bundle css
            find . -name "*.css" | while read f; do
              postcss $f --replace --use autoprefixer
              cleancss --output $f $f
            done
            # bundle html
            find . -name "*.html" | while read f; do
              html-minifier --collapse-boolean-attributes \
                            --collapse-whitespace \
                            --minify-css true \
                            --minify-js true \
                            --output $f \
                            --remove-attribute-quotes \
                            --remove-comments \
                            --remove-empty-attributes \
                            --remove-optional-tags \
                            --remove-redundant-attributes \
                            --remove-script-type-attributes \
                            --remove-style-link-type-attributes \
                            --use-short-doctype \
                            $f
            done
            # bundle javascript
            find . -name "*.js" | while read f; do
              terser --compress --mangle --module --output $f $f
            done
          )

      - name: Deploy to https://carnarez.github.io/polars-unpack/
        run: |
          (
            cd web
            ghp-import --branch www --force --push /tmp/www
          )
