name: Run Python tests

on:
  push:
    path:
      - '**.py'

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout https://github.com/carnarez/polars-unpack repository
        uses: actions/checkout@v3

      - name: Set up Python v3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --no-cache-dir polars pytest pytest-cov

      - name: Run pytest
        run: |
          python -m pytest --color=yes --cov=unpack --cov-report term-missing --verbose
